- name: Pocket ID user
  ansible.builtin.user:
    name: pocket-id
    shell: /usr/sbin/nologin
    create_home: true
- name: Getent passwd
  ansible.builtin.getent:
    database: passwd
  changed_when: false
- name: Set pocket-id uid
  ansible.builtin.set_fact:
    pocket_id_uid: "{{ getent_passwd['pocket-id'].1 }}"
  changed_when: false
- name: Pocket ID data directory
  ansible.builtin.file:
    path: "{{ pocket_id_directory }}"
    state: directory
    mode: '0750'
    owner: pocket-id
    group: pocket-id
    recurse: true
- name: Pocket ID Litestream private key
  ansible.builtin.copy:
    src: litestream.key
    dest: "{{ pocket_id_directory }}/ssh-key"
    mode: '0640'
    owner: pocket-id
    group: pocket-id
  when: pocket_id_role == 'primary'
- name: Pocket ID Litestream public key
  ansible.posix.authorized_key:
    user: pocket-id
    key: "{{ lookup('file', 'litestream.pub') }}"
    state: "{{ 'present' if (pocket_id_role == 'secondary' and pocket_id_state == 'present') else 'absent' }}"
  when: pocket_id_role == 'secondary'
- name: Pocket ID encryption key
  ansible.builtin.copy:
    src: encryption.key
    dest: "{{ pocket_id_directory }}/encryption-key.txt"
    mode: '0640'
    owner: pocket-id
    group: pocket-id
  notify: Restart Pocket ID
- name: Pocket ID service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "pocket-id"
    docker_service_description: "Pocket ID"
    docker_service_image: ghcr.io/pocket-id/pocket-id:v1
    docker_service_network: source_default
    docker_service_enabled: "{{ pocket_id_role == 'primary' }}"
    docker_service_state: "{{ pocket_id_state }}"
    docker_service_env_vars:
      APP_URL: "https://pocket-id.srv.simpson.id"
      ENCRYPTION_KEY_FILE: "/data/encryption-key.txt"
      TRUST_PROXY: "true"
      PUID: "{{ pocket_id_uid }}"
      PGID: "{{ pocket_id_uid }}"
      DB_CONNECTION_STRING: "file:/data/pocket-id.db?_pragma=journal_mode(WAL)&_pragma=busy_timeout(2500)&_txlock=immediate"
      FILE_BACKEND: "database"
      KEYS_STORAGE: "database"
      UI_CONFIG_DISABLED: "true"
      SMTP_FROM: "pocket-id@ses.simpson.id"
      SMTP_USER: "{{ smtp_username }}"
      SMTP_PASSWORD: "{{ smtp_password }}"
      SMTP_HOST: "{{ smtp_hostname }}"
      SMTP_PORT: "{{ smtp_port }}"
      SMTP_TLS: "{{ smtp_tls }}"
    docker_service_volumes:
      - "{{ pocket_id_directory }}:/data"
