---
- name: Nginx directories
  ansible.builtin.file:
    path: "{{ nginx_directory }}/{{ item }}"
    state: directory
    owner: app
    group: app
    mode: '0750'
  loop:
    - ""
    - "sites.d"

- name: Nginx config file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_directory }}/nginx.conf"
    owner: app
    group: app
    mode: '0640'
