- name: Renovate directory
  ansible.builtin.file:
    path: /srv/renovate
    state: directory
    owner: app
    group: app
    mode: '0750'
- name: Renovate config file
  ansible.builtin.copy:
    content: |
      {
        "repositories": [ "samsimpson1/ansible" ]
      }
    dest: /srv/renovate/config.json
    owner: app
    group: app
    mode: "0640"
- name: Renovate GitHub App key
  ansible.builtin.copy:
    src: github_app.pem
    dest: /srv/renovate/github_app.pem
    owner: app
    group: app
    mode: '0600'
- name: Renovate GitHub App installation token script
  ansible.builtin.template:
    src: installation_token.sh.j2
    dest: /srv/renovate/installation_token.sh
    owner: app
    group: app
    mode: "0750"
- name: Renovate start script
  ansible.builtin.template:
    src: start.sh.j2
    dest: /srv/renovate/start.sh
    owner: app
    group: app
    mode: "0750"
- name: Renovate cron job
  ansible.builtin.cron:
    name: "Renovate"
    user: app
    minute: "28"
    job: "/srv/renovate/start.sh"
