- name: HA Proxy
  hosts:
    - box
    - little
  become: true
  tasks:
    - name: App user
      ansible.builtin.include_tasks: apps/app-user.yaml
    - name: ACME Manager
      ansible.builtin.include_role:
        name: acme_manager
      tags: acme
      when: inventory_hostname == 'little'
    - name: ACME Client
      ansible.builtin.include_role:
        name: acme_client
      when: inventory_hostname != 'little'
      tags: acme
    - name: HA Proxy
      ansible.builtin.include_role:
        name: ha_proxy
      tags: ha_proxy