- name: UniFi port forwards
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  vars_files:
    - vars/unifi.yaml
  module_defaults:
    unifi_port_forward:
      api_url: "{{ unifi_host }}"
      api_key: "{{ unifi_api_key }}"
      validate_certs: false
      site: default
  tasks:
    - name: Forgejo SSH (22)
      unifi_port_forward:
        name: "Forgejo SSH (22)"
        state: "present"
        protocol: "tcp_udp"
        wan:
          ip_address: "158.173.147.115"
          port: "22"
        forward:
          ip: "10.0.0.202"
          port: "2689"
    - name: Forgejo SSH (2689)
      unifi_port_forward:
        name: "Forgejo SSH (2689)"
        state: "present"
        protocol: "tcp_udp"
        wan:
          ip_address: "158.173.147.115"
          port: "2689"
        forward:
          ip: "10.0.0.202"
          port: "2689"