- name: Box
  hosts: box
  vars_files:
    - vars/concourse.yaml
  become: true
  tasks:
    - name: Forgejo
      ansible.builtin.include_role:
        name: forgejo

    - name: Nginx
      ansible.builtin.include_role:
        name: nginx
      vars:
        nginx_state: absent

    - name: App user
      ansible.builtin.include_tasks: apps/app-user.yaml

    - name: Tailscale
      ansible.builtin.include_role:
        name: tailscale

    - name: Docker
      ansible.builtin.include_role:
        name: docker_host

    - name: App data disk directory
      ansible.builtin.file:
        path: /mnt/app
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Mount app data device
      ansible.posix.mount:
        path: /mnt/app
        src: UUID=050ce107-d3d2-448a-a5bf-1f8fe15e3c3f
        state: mounted
        fstype: ext4
        opts: defaults,noatime

    - name: Root app data directory
      ansible.builtin.file:
        path: /mnt/app/data
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: App data directory
      ansible.builtin.file:
        path: /srv/app
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: App data bind mount
      ansible.posix.mount:
        path: /srv/app
        src: /mnt/app/data
        state: mounted
        fstype: none
        opts: bind

    - name: GitHub Actions SSH key
      ansible.posix.authorized_key:
        user: me
        state: present
        key: "{{ lookup('file', 'github-actions.pub') }}"

    - name: ACME Client
      ansible.builtin.include_role:
        name: acme_client

    - name: Concourse Web
      ansible.builtin.include_role:
        name: concourse_web
      vars:
        concourse_web_data_directory: "/srv/app/concourse"
        concourse_web_external_url: "https://ci.srv.simpson.id"
        concourse_web_session_signing_key: "{{ concourse_session_signing_key }}"
        concourse_web_tsa_host_key: "{{ concourse_tsa_host_key }}"
        concourse_web_tsa_authorized_keys: "{{ concourse_worker_key_pub }}"
        concourse_web_onepassword_service_account_token: "{{ concourse_onepassword_service_account_token }}"
        concourse_web_vault_token: "{{ concourse_vault_token }}"

    - name: Concourse Worker
      ansible.builtin.include_role:
        name: concourse_worker
      vars:
        concourse_worker_tsa_public_key: "{{ concourse_tsa_host_key_pub }}"
        concourse_worker_worker_key: "{{ concourse_worker_key }}"

    - name: Knot
      ansible.builtin.include_role:
        name: knot

    - name: Pocket ID
      ansible.builtin.include_role:
        name: pocket_id
      vars:
        pocket_id_role: secondary
        pocket_id_directory: "/srv/app/pocket-id"
        pocket_id_app_name: "Pocket ID (Backup)"
        pocket_id_accent_colour: "red"

    - name: Caddy external
      ansible.builtin.include_role:
        name: caddy
      vars:
        caddy_id: "external"
        caddy_https_port: "6997"
        caddy_http_port: "6996"
        caddy_env_vars: {}
        caddy_hosts: "{{ sites | selectattr('kind', 'equalto', 'external') }}"
        caddy_data_directory: "/srv/app/caddy"
        caddy_networks: ["concourse", "knot", "pocket_id", "forgejo"]
