- name: Little (infra)
  hosts: little
  become: true
  tasks:
    - name: GitHub Actions SSH key
      ansible.posix.authorized_key:
        user: me
        state: present
        key: "{{ lookup('file', 'github-actions.pub') }}"

    - name: Tailscale
      ansible.builtin.include_role:
        name: tailscale

    - name: Docker
      ansible.builtin.include_role:
        name: docker_host

    - name: SSMTP
      ansible.builtin.include_role:
        name: ssmtp

    - name: Caddy
      ansible.builtin.include_tasks: apps/caddy.yaml

    - name: Pocket ID
      ansible.builtin.include_role:
        name: pocket_id
      vars:
        pocket_id_role: primary


    - name: Monitoring server
      ansible.builtin.include_role:
        name: monitoring_server
      vars:
        monitoring_server_grafana_extra_volumes:
          - "/srv/containers/storage/ssd/stonks:/stonks:rw"
          - "/srv/containers/storage/ssd/nutrition:/nutrition:rw"

    - name: Vault
      ansible.builtin.include_role:
        name: vault

