- name: Little (media)
  hosts: little
  become: true
  tasks:
    - name: Arr apps
      ansible.builtin.include_tasks: apps/arr.yaml
      tags:
        - arr
        - prowlarr
        - radarr
        - sonarr
    - name: Downloader apps
      ansible.builtin.include_tasks: apps/downloaders.yaml
      tags:
        - downloaders
        - qbittorrent
        - sabnzbd
        - unpackerr
        - slskd
    - name: Media frontend apps
      ansible.builtin.include_tasks: apps/media-frontend.yaml
      tags:
        - media-frontend
        - audiobookshelf
        - plex
        - jellyfin
        - lms
        - navidrome
        - komga
        - overseerr
        - pinchflat

    - name: Kavita
      ansible.builtin.include_role:
        name: kavita