- name: Little (media)
  hosts: little
  become: true
  tasks:
    - name: Arr apps
      ansible.builtin.include_tasks: apps/arr.yaml
      tags:
        - arr
        - prowlarr
        - radarr
        - sonarr
    - name: Downloader apps
      ansible.builtin.include_tasks: apps/downloaders.yaml
      tags:
        - downloaders
        - qbittorrent
        - sabnzbd
        - unpackerr
        - slskd
    - name: Media frontend apps
      ansible.builtin.include_tasks: apps/media-frontend.yaml
      tags:
        - media-frontend
        - audiobookshelf
        - plex
        - jellyfin
        - lms
        - navidrome
        - komga
        - overseerr
        - pinchflat

    - name: Kavita docker network
      community.docker.docker_network:
        name: kavita
        state: present

    - name: Kavita
      ansible.builtin.include_role:
        name: kavita
      vars:
        kavita_network: [source_default, kavita]

    - name: Kavita nginx site
      ansible.builtin.include_role:
        name: nginx_site
      vars:
        nginx_site_name: kavita
        nginx_site_state: present
        nginx_site_kind: internal
        nginx_site_server_names: [books.int.simpson.id]
        nginx_site_certificate: int.simpson.id
        nginx_site_upstream: "http://kavita:5000"
        nginx_site_networks: [kavita]