- name: Little (apps)
  hosts: little
  become: true
  vars_files:
    - vars/apple-music-gateway.yaml
  tasks:
    - name: Wiki
      ansible.builtin.include_tasks: apps/wiki.yaml
      tags:
        - wiki
    - name: Karakeep
      ansible.builtin.include_tasks: apps/karakeep.yaml
      tags:
        - karakeep
    - name: FreshRSS
      ansible.builtin.include_tasks: apps/freshrss.yaml
      tags:
        - freshrss
    - name: Home Assistant
      ansible.builtin.include_tasks: apps/home-assistant.yaml
      tags:
        - home-assistant
    - name: Miscellaneous
      ansible.builtin.include_tasks: apps/misc.yaml
      tags:
        - misc
    - name: Catbot
      ansible.builtin.include_tasks: apps/catbot.yaml
      tags:
        - catbot
    - name: Samba server
      ansible.builtin.include_role:
        name: samba_server
      tags:
        - samba
    - name: Stonks scraper
      ansible.builtin.include_tasks: apps/stonks-scraper.yaml
      tags:
        - stonks
    - name: Apple Music gateway
      ansible.builtin.include_tasks: apps/apple-music-gateway.yaml