- name: Box (backup)
  hosts: box
  become: true
  vars_files:
    - vars/backup.yaml
  tasks:
    - name: Backup
      ansible.builtin.include_role:
        name: backup
      vars:
        backup_jobs:
          - name: box-concourse
            op: restic
            path: /srv/app/concourse
            cron:
              minute: "49"
              hour: "*/6"
          - name: box-knot
            op: restic
            path: /srv/app/knot
            cron:
              minute: "58"
              hour: "*/2"
          - name: box-forgejo
            op: restic
            path: /srv/app/forgejo
            cron:
              minute: "11"
              hour: "*/3"