- name: Little (backup)
  hosts: little
  vars_files:
    - vars/backup.yaml
  become: true
  tasks:
    - name: Duplicacy user
      ansible.builtin.include_tasks: apps/duplicacy-backup.yaml
      tags:
        - duplicacy
    # desktop backup access
    - name: Desktop restic SSH authorised key
      ansible.posix.authorized_key:
        user: me
        key: "{{ lookup('file', 'desktop/backup-linux/files/ssh-key.pub') }}"
        comment: restic
    - name: Backup
      ansible.builtin.include_role:
        name: backup
      vars:
        backup_jobs:
          - name: duplicacy
            op: sync
            path: /srv/containers/storage/hdd/duplicacy-backup/
            cron:
              minute: "30"
              hour: "*/6"
          - name: file-storage
            op: restic
            path: /srv/containers/storage/hdd/files/
            cron:
              minute: "19"
              hour: "*/2"
          - name: karakeep
            op: restic
            path: /srv/containers/storage/ssd/karakeep/
            cron:
              minute: "14"
              hour: "*/2"
          - name: pocket-id
            op: restic
            path: /srv/containers/storage/ssd/pocket-id/
            cron:
              minute: "18"
              hour: "*/2"
          - name: desktop-restic
            op: sync
            path: /srv/containers/storage/hdd/restic-backup/
            cron:
              minute: "49"
              hour: "*/6"
          - name: sabnzbd
            op: restic
            path: /srv/containers/storage/ssd/sabnzbd/
            cron:
              minute: "17"
              hour: "5"
            excludes: "/srv/containers/storage/ssd/sabnzbd/Downloads/*"
          - name: stonks
            op: restic
            path: /srv/containers/storage/ssd/stonks/
            cron:
              minute: "16"
              hour: "*/4"
          - name: vault
            op: restic
            path: /srv/containers/storage/ssd/vault/
            cron:
              minute: "11"
              hour: "*/2"
          - name: certificates
            op: restic
            path: /srv/certificates
            cron:
              minute: "0"
              hour: "5"
      tags:
        - backup

    - name: Offline Backup
      ansible.builtin.include_role:
        name: offline_backup
      tags:
        - offline-backup

    - name: Create storage box metrics cron job
      ansible.builtin.cron:
        name: "Storage Box Metrics"
        user: root
        minute: "*/20"
        job: >
          /usr/bin/env docker run
          --rm --pull always
          -e HCLOUD_TOKEN={{ backup_hcloud_token }}
          ghcr.io/samsimpson1/storage-box-metrics:latest
          backup-box
      tags:
        - storage-box-metrics
