- name: Little (apps)
  hosts: little
  vars_files:
    - secret.yaml
  become: true
  tasks:
    - name: Wiki
      ansible.builtin.include_tasks: apps/wiki.yaml
    - name: ECG notify
      ansible.builtin.include_role:
        name: ecg_notify
    - name: Karakeep
      ansible.builtin.include_tasks: apps/karakeep.yaml
    - name: FreshRSS
      ansible.builtin.include_tasks: apps/freshrss.yaml
    - name: Arr apps
      ansible.builtin.include_tasks: apps/arr.yaml
    - name: Downloader apps
      ansible.builtin.include_tasks: apps/downloaders.yaml
    - name: Media frontend apps
      ansible.builtin.include_tasks: apps/media-frontend.yaml
    - name: Firefly III
      ansible.builtin.include_role:
        name: firefly_iii
