- hosts: little
  vars_files:
    - secret.yaml
  become: true
  tasks:
    - name: Tailscale
      include_role:
        name: tailscale
    - name: Docker
      include_role:
        name: docker-host
    - name: Pocket ID
      ansible.builtin.include_tasks: apps/pocket-id.yaml
    - name: Karakeep
      ansible.builtin.include_tasks: apps/karakeep.yaml
    - name: FreshRSS
      ansible.builtin.include_tasks: apps/freshrss.yaml