- name: Little (apps)
  hosts: little
  vars_files:
    - secret.yaml
  become: true
  tasks:
    - name: Wiki
      ansible.builtin.include_tasks: apps/wiki.yaml
    - name: ECG notify
      ansible.builtin.include_role:
        name: ecg_notify
    - name: Karakeep
      ansible.builtin.include_tasks: apps/karakeep.yaml
    - name: FreshRSS
      ansible.builtin.include_tasks: apps/freshrss.yaml
    - name: Arr apps
      ansible.builtin.include_tasks: apps/arr.yaml
    - name: Downloader apps
      ansible.builtin.include_tasks: apps/downloaders.yaml
    - name: Media frontend apps
      ansible.builtin.include_tasks: apps/media-frontend.yaml
    - name: Firefly III
      ansible.builtin.include_role:
        name: firefly_iii
    - name: Home Assistant
      ansible.builtin.include_tasks: apps/home-assistant.yaml
    - name: Monitoring
      ansible.builtin.include_tasks: apps/monitoring.yaml
    - name: Miscellaneous
      ansible.builtin.include_tasks: apps/misc.yaml
    - name: Renovate
      ansible.builtin.include_role:
        name: renovate
    - name: Catbot
      ansible.builtin.include_tasks: apps/catbot.yaml
    - name: Samba server
      ansible.builtin.include_role:
        name: samba_server
    - name: Stonks scraper
      ansible.builtin.include_tasks: apps/stonks-scraper.yaml
    - name: File storage
      ansible.builtin.include_tasks: apps/file-storage.yaml
