- hosts: little
  vars_files:
    - secret.yaml
  become: true
  tasks:
    - name: Tailscale
      include_role:
        name: tailscale
    - name: Docker
      include_role:
        name: docker-host
    - name: Miscellaneous applications
      ansible.builtin.include_tasks: apps-misc.yaml
