- name: Charon
  hosts: charon
  vars_files:
    - secret.yaml
  become: true
  tasks:
    - name: Configure netplan
      ansible.builtin.copy:
        content: |
          network:
            version: 2
            ethernets:
              eth0:
                optional: true
                dhcp4: true
                dhcp4-overrides:
                  route-metric: 100
                  use-routes: true
              enx54af97ab9a64:
                optional: true
                dhcp4: true
                dhcp4-overrides:
                  route-metric: 200
        dest: /etc/netplan/50-cloud-init.yaml
        owner: root
        group: root
        mode: '0600'
      register: netplan_config
    - name: Apply netplan
      ansible.builtin.command: netplan apply
      when: netplan_config.changed
    - name: GitHub Actions SSH key
      ansible.posix.authorized_key:
        user: me
        state: present
        key: "{{ lookup('file', 'github-actions.pub') }}"
    - name: Tailscale
      ansible.builtin.include_role:
        name: tailscale
    - name: Docker
      ansible.builtin.include_role:
        name: docker_host
