- name: HA Proxy
  hosts:
    - box
    - little
  become: true
  tasks:
    - name: App user
      ansible.builtin.include_tasks: apps/app-user.yaml
    - name: ACME Client
      ansible.builtin.include_role:
        name: acme_client
      when: inventory_hostname != 'little'
    - name: HA Proxy Role
      ansible.builtin.include_role:
        name: ha_proxy
