- name: Monitoring
  hosts: home
  become: true
  tasks:
    - name: SSMTP
      ansible.builtin.include_role:
        name: ssmtp
    - name: Include monitoring tasks
      ansible.builtin.include_role:
        name: monitoring
