- name: Little (infra)
  hosts: little
  vars_files:
    - container-images.yaml
    - secret.yaml
  become: true
  tasks:
    - name: GitHub Actions SSH key
      ansible.posix.authorized_key:
        user: me
        state: present
        key: "{{ lookup('file', 'github-actions.pub') }}"
    - name: Tailscale
      ansible.builtin.include_role:
        name: tailscale
    - name: APC UPS Daemon (Client)
      ansible.builtin.include_role:
        name: apcupsd
      vars:
        apcupsd_mode: client
        apcupsd_upsname: BoxUPS
        apcupsd_server: box
        apcupsd_batterylevel: 10
        apcupsd_minutes: 5
    - name: Docker
      ansible.builtin.include_role:
        name: docker_host
    - name: SSMTP
      ansible.builtin.include_role:
        name: ssmtp
    - name: ACME Manager
      ansible.builtin.include_role:
        name: acme_manager
      vars:
        acme_manager_cloudflare_account_id: "{{ cloudflare_account_id }}"
        acme_manager_cloudflare_account_token: "{{ cloudflare_account_token }}"
    - name: Caddy
      ansible.builtin.include_tasks: apps/caddy.yaml
