- name: Monitoring
  hosts: home
  vars_files:
    - secret.yaml
  become: true
  tasks:
    - name: Docker
      ansible.builtin.include_role:
        name: docker_host

    - name: Monitoring exporters
      ansible.builtin.include_role:
        name: monitoring_exporters
