- name: Little (infra)
  hosts: little
  vars_files:
    - container-images.yaml
    - secret.yaml
    - vars/sites.yaml
  become: true
  tasks:
    - name: GitHub Actions SSH key
      ansible.posix.authorized_key:
        user: me
        state: present
        key: "{{ lookup('file', 'github-actions.pub') }}"
    - name: Tailscale
      ansible.builtin.include_role:
        name: tailscale
    - name: Docker
      ansible.builtin.include_role:
        name: docker_host
    - name: SSMTP
      ansible.builtin.include_role:
        name: ssmtp
    - name: Caddy
      ansible.builtin.include_tasks: apps/caddy.yaml
