---
- name: Present tasks
  ansible.builtin.include_tasks:
    file: present.yaml
  when: caddy_state == 'present'

- name: Caddy service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "caddy-{{ caddy_id }}"
    docker_service_description: "Caddy {{ caddy_id }}"
    docker_service_image: "localhost/{{ caddy_id }}-{{ container_images.caddy }}"
    docker_service_pull_policy: "never"
    docker_service_network: "{{ caddy_networks }}"
    docker_service_user: "568"
    docker_service_groups: "{{ caddy_all_groups | default([]) }}"
    docker_service_command: "caddy run -c /Caddyfile"
    docker_service_env_vars: "{{ caddy_env_vars }}"
    docker_service_ports: "{{ caddy_ports | default([]) }}"
    docker_service_volumes: "{{ (caddy_volumes_standard | default([])) + (caddy_volumes | default([])) }}"
    docker_service_state: "{{ caddy_state }}"

- name: Absent tasks
  ansible.builtin.include_tasks:
    file: absent.yaml
  when: caddy_state == 'absent'
