- name: Shell (SSH)
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Set Facts (MacOS)
      ansible.builtin.set_fact:
        ssh_askpass: "/set/later"
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Set Facts (Linux)
      ansible.builtin.set_fact:
        ssh_askpass: "/usr/bin/ksshaskpass"
      when: ansible_facts['os_family'] == 'Archlinux'

    - name: Create SSH key handles
      ansible.builtin.copy:
        dest: "{{ ansible_facts['user_dir'] }}/.ssh/{{ item }}"
        src: "files/{{ item }}"
        mode: '0600'
        owner: "{{ ansible_facts['user_uid'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
      loop:
        - yubi1.key
        - yubi1.pub
        - yubi2.key
        - yubi2.pub

    - name: Create ssh-agent zshrc script
      ansible.builtin.copy:
        dest: "{{ ansible_facts['user_dir'] }}/.zshrc.d/ssh-agent-yubi.zsh"
        content: |
          eval $(ssh-agent)
          ssh-add -q $HOME/.ssh/yubi1.key $HOME/.ssh/yubi2.key
        mode: '0750'
        owner: "{{ ansible_facts['user_uid'] }}"
        group: "{{ ansible_facts['user_gid'] }}"

    - name: Create gitconfig
      ansible.builtin.copy:
        src: files/gitconfig
        dest: "{{ ansible_facts['user_dir'] }}/.gitconfig"
        mode: '0640'
        owner: "{{ ansible_facts['user_uid'] }}"
        group: "{{ ansible_facts['user_gid'] }}"