
- name: Create copyparty directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
    owner: copyparty
    group: copyparty
    mode: '0750'
  loop:
    - "{{ copyparty_config_dir }}"
- name: Copyparty service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: copyparty
    docker_service_image: "{{ container_images.copyparty }}"
    docker_service_state: "{{ copyparty_state }}"
    docker_service_user: "{{ copyparty_uid }}"
    docker_service_network: "source_default"
    docker_service_volumes:
      - "{{ copyparty_config_dir }}:/cfg"
      - "{{ copyparty_private_dir }}:/private"
      - "{{ copyparty_share_dir }}:/files"
- name: Copyparty user
  ansible.builtin.user:
    name: copyparty
    state: absent
    system: true
    create_home: false