---
- name: Present tasks
  ansible.builtin.include_tasks:
    file: present.yaml
  when: monitoring_server_state == 'present'

- name: Alertmanager service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "alertmanager"
    docker_service_description: "Prometheus Alertmanager"
    docker_service_image: "{{ container_images.alertmanager }}"
    docker_service_network: "{{ monitoring_server_network }}"
    docker_service_user: "{{ monitoring_server_user }}"
    docker_service_groups: ["{{ monitoring_server_group }}"]
    docker_service_command: "--config.file=/etc/alertmanager/config.yaml --storage.path=/alertmanager"
    docker_service_volumes:
      - "{{ monitoring_server_storage_path }}/alertmanager:/alertmanager:rw"
      - "{{ monitoring_server_storage_path }}/alertmanager/config.yaml:/etc/alertmanager/config.yaml:ro"
      - "{{ monitoring_server_storage_path }}/alertmanager/templates.tmpl:/etc/alertmanager/templates/discord.tmpl:ro"
    docker_service_state: "{{ monitoring_server_state }}"

- name: Prometheus Pushgateway service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "prometheus-pushgateway"
    docker_service_description: "Prometheus Pushgateway"
    docker_service_image: "{{ container_images.prometheus_pushgateway }}"
    docker_service_network: "{{ monitoring_server_network }}"
    docker_service_user: "{{ monitoring_server_user }}"
    docker_service_groups: ["{{ monitoring_server_group }}"]
    docker_service_state: "{{ monitoring_server_state }}"

- name: Prometheus service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "prometheus"
    docker_service_description: "Prometheus"
    docker_service_image: "{{ container_images.prometheus }}"
    docker_service_network: "{{ monitoring_server_network }}"
    docker_service_user: "{{ monitoring_server_user }}"
    docker_service_groups: ["{{ monitoring_server_group }}"]
    docker_service_command: >-
      --storage.tsdb.path /data
      --storage.tsdb.retention.size {{ monitoring_server_prometheus_retention_size }}
      --config.file /config.yaml
    docker_service_volumes:
      - "{{ monitoring_server_storage_path }}/prometheus:/data:rw"
      - "{{ monitoring_server_storage_path }}/prometheus/config.yaml:/config.yaml:ro"
      - "{{ monitoring_server_storage_path }}/prometheus/alerts.yaml:/alerts.yaml:ro"
    docker_service_state: "{{ monitoring_server_state }}"

- name: Grafana service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "grafana"
    docker_service_description: "Grafana"
    docker_service_image: "{{ container_images.grafana }}"
    docker_service_network: "{{ monitoring_server_network }}"
    docker_service_user: "{{ monitoring_server_user }}"
    docker_service_groups: ["{{ monitoring_server_group }}"]
    docker_service_env_vars:
      GF_SERVER_ROOT_URL: "{{ monitoring_server_grafana_root_url }}"
    docker_service_volumes: "{{ [monitoring_server_storage_path + '/grafana:/var/lib/grafana:rw'] + monitoring_server_grafana_extra_volumes }}"
    docker_service_state: "{{ monitoring_server_state }}"

- name: Absent tasks
  ansible.builtin.include_tasks:
    file: absent.yaml
  when: monitoring_server_state == 'absent'
