---
- name: Present tasks
  ansible.builtin.include_tasks:
    file: present.yaml
  when: oauth2_proxy_state == 'present'

- name: OAuth2 Proxy service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "{{ oauth2_proxy_id }}-oauth2-proxy"
    docker_service_description: "{{ oauth2_proxy_description | default('OAuth2 Proxy for ' + oauth2_proxy_id) }}"
    docker_service_image: "{{ oauth2_proxy_image }}"
    docker_service_network: "{{ oauth2_proxy_network }}"
    docker_service_user: "{{ oauth2_proxy_user }}"
    docker_service_groups: ["{{ oauth2_proxy_group }}"]
    docker_service_command: "oauth2-proxy --config=/oauth2-proxy.cfg"
    docker_service_volumes:
      - "/srv/containers/storage/ssd/{{ oauth2_proxy_id }}-oauth2-proxy/oauth2-proxy.cfg:/oauth2-proxy.cfg:ro"
    docker_service_state: "{{ oauth2_proxy_state }}"

- name: Absent tasks
  ansible.builtin.include_tasks:
    file: absent.yaml
  when: oauth2_proxy_state == 'absent'
