container_images:
  caddy: caddy:2.10
  node_exporter: prom/node-exporter:v1.10.2
  smartctl_exporter: prometheuscommunity/smartctl-exporter:v0.14.0
  prometheus: prom/prometheus:v3.9.1
  prometheus_pushgateway: prom/pushgateway:v1.11.2
  alertmanager: prom/alertmanager:v0.30.0
  grafana: grafana/grafana:12.3.1
  copyparty: ghcr.io/9001/copyparty-iv:1.19.23
  concourse_web: concourse/concourse:7.14.3
  concourse_worker: concourse/concourse:7.14.3
  concourse_postgres: postgres:18
  vault: hashicorp/vault:1.21.2
  knot: tngl/knot:v1.10.0-alpha
  filebrowser: ghcr.io/gtsteffaniak/filebrowser:1.1.0-stable
  litestream: litestream/litestream:0.5.5
  pocket_id: ghcr.io/pocket-id/pocket-id:v2.1.0
  oauth2_proxy: quay.io/oauth2-proxy/oauth2-proxy:v7.11.0
  samba: quay.io/samba.org/samba-server:latest
  prowlarr: ghcr.io/home-operations/prowlarr:2.3
  radarr: ghcr.io/home-operations/radarr:6.1.1
  sonarr: ghcr.io/home-operations/sonarr:4.0.16
  qbittorrent: ghcr.io/home-operations/qbittorrent:5.1.4
  sabnzbd: ghcr.io/home-operations/sabnzbd:4.5.5
  unpackerr: ghcr.io/unpackerr/unpackerr:0.14.5
  slskd: slskd/slskd:0.24.1
  plex: ghcr.io/home-operations/plex:rolling
  jellyfin: jellyfin/jellyfin:latest
  audiobookshelf: ghcr.io/advplyr/audiobookshelf:2.32.1
  lyrion: lmscommunity/lyrionmusicserver:9.1.0
  navidrome: deluan/navidrome:latest
  komga: ghcr.io/gotson/komga:1.23.6
  overseerr: ghcr.io/sct/overseerr:1.34.0
  pinchflat: ghcr.io/kieraneglin/pinchflat:v2025.6.6
  freshrss: freshrss/freshrss:1.28.0
  home_assistant: ghcr.io/home-assistant/home-assistant:2026.1.0
  karakeep: ghcr.io/karakeep-app/karakeep:0.30.0
  karakeep_meilisearch: getmeili/meilisearch:v1.13.3
  alpine_chrome: gcr.io/zenika-hub/alpine-chrome:124