container_images:
  caddy: caddy:2.10
  node_exporter: prom/node-exporter:v1.12.0
  smartctl_exporter: prometheuscommunity/smartctl-exporter:v0.14.0
  prometheus: prom/prometheus:v3.13.1
  prometheus_pushgateway: prom/pushgateway:v1.11.2
  alertmanager: prom/alertmanager:v0.33.1
  grafana: grafana/grafana:12.4.5
  concourse_web: concourse/concourse:8.2.4
  concourse_worker: concourse/concourse:8.2.4
  concourse_postgres: postgres:18
  vault: hashicorp/vault:2.0.2
  knot: tngl/knot:v1.10.0-alpha
  filebrowser: ghcr.io/gtsteffaniak/filebrowser:1.2.1-stable
  litestream: litestream/litestream:0.5.6
  pocket_id: ghcr.io/pocket-id/pocket-id:v2.11.0
  oauth2_proxy: quay.io/oauth2-proxy/oauth2-proxy:v7.14.3
  samba: quay.io/samba.org/samba-server:latest
  prowlarr: ghcr.io/home-operations/prowlarr:2.5
  radarr: ghcr.io/home-operations/radarr:6.3.0
  sonarr: ghcr.io/home-operations/sonarr:4.0.18
  lidarr: ghcr.io/home-operations/lidarr:3.1.3
  qbittorrent: ghcr.io/home-operations/qbittorrent:5.2.3
  sabnzbd: ghcr.io/home-operations/sabnzbd:5.0.4
  unpackerr: ghcr.io/unpackerr/unpackerr:0.15.2
  slskd: slskd/slskd:0.25.1
  plex: ghcr.io/home-operations/plex:rolling
  jellyfin: jellyfin/jellyfin:latest
  audiobookshelf: ghcr.io/advplyr/audiobookshelf:2.35.1
  lyrion: lmscommunity/lyrionmusicserver:9.2.0
  navidrome: deluan/navidrome:latest
  overseerr: ghcr.io/sct/overseerr:1.35.0
  pinchflat: ghcr.io/kieraneglin/pinchflat@sha256:01b4f98aabaf3f5fe394213f7a32578c9e84e42080f52e2f8334021a4473b202 # v2025.9.26
  freshrss: freshrss/freshrss:1.28.1
  home_assistant: ghcr.io/home-assistant/home-assistant:2026.4.4
  karakeep: ghcr.io/karakeep-app/karakeep:0.32.0
  karakeep_meilisearch: getmeili/meilisearch:v1.13.3
  alpine_chrome: gcr.io/zenika-hub/alpine-chrome:124
  nginx: nginx:1.31.1
  forgejo: codeberg.org/forgejo/forgejo:15.0.4
  stonks_scraper: ghcr.io/samsimpson1/stonks:2026.2.12-125036
  kavita: ghcr.io/kareadita/kavita:0.9.0
  nextcloud_aio: ghcr.io/nextcloud-releases/all-in-one:20260515_145717