container_images:
  caddy: caddy:2.10
  node_exporter: prom/node-exporter:v1.10.2
  smartctl_exporter: prometheuscommunity/smartctl-exporter:v0.14.0
  prometheus: prom/prometheus:v3.8.1
  prometheus_pushgateway: prom/pushgateway:v1.11.2
  alertmanager: prom/alertmanager:v0.30.0
  grafana: grafana/grafana:12.3.1
  copyparty: ghcr.io/9001/copyparty-iv:1.19.23
  concourse_web: concourse/concourse:7.14.3
  concourse_worker: concourse/concourse:7.14.3
  concourse_postgres: postgres:18
  vault: hashicorp/vault:1.21.1
  knot: tngl/knot:v1.10.0-alpha
  filebrowser: ghcr.io/gtsteffaniak/filebrowser:1.1.0-stable
  litestream: litestream/litestream:0.5.5
  pocket_id: ghcr.io/pocket-id/pocket-id:v2.0.1