---
- name: Remove backup job cron entries
  ansible.builtin.cron:
    name: "Backup {{ item.op }} {{ item.name }}"
    state: absent
    user: root
  loop: "{{ backup_jobs }}"

- name: Remove prune job cron entries
  ansible.builtin.cron:
    name: "Prune {{ item.op }} {{ item.name }}"
    state: absent
    user: root
  loop: "{{ backup_jobs }}"
  when: item.op == 'restic'

- name: Remove backup directory
  ansible.builtin.file:
    path: /srv/backups
    state: absent
