---
- name: Present tasks
  ansible.builtin.include_tasks:
    file: present.yaml
  when: filebrowser_state == 'present'

- name: Filebrowser container service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: filebrowser
    docker_service_description: "Filebrowser Quantum"
    docker_service_image: "{{ container_images.filebrowser }}"
    docker_service_network: "{{ filebrowser_network }}"
    docker_service_state: "{{ filebrowser_state }}"
    docker_service_user: "568"
    docker_service_groups: ["568"]
    docker_service_volumes:
      - "{{ filebrowser_config_directory }}:/config"
      - "{{ filebrowser_files_directory }}:/files"
    docker_service_env_vars:
      FILEBROWSER_CONFIG: "/config/config.yaml"

- name: Absent tasks
  ansible.builtin.include_tasks:
    file: absent.yaml
  when: filebrowser_state == 'absent'
