- name: Firefly III data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: app
    group: app
    mode: '0755'
  loop:
    - /srv/containers/storage/ssd/firefly-iii
    - /srv/containers/storage/ssd/firefly-iii/upload
    - /srv/containers/storage/ssd/firefly-iii/db
- name: Firefly III OAuth2 Proxy
  ansible.builtin.include_role:
    name: oauth2_proxy
  vars:
    oauth2_proxy_id: "firefly"
    oauth2_proxy_upstreams:
      - "http://firefly-iii:8080"
    oauth2_proxy_skip_auth_routes:
      - "^/api"
    oauth2_proxy_client_id: "{{ sso_clients.firefly_iii.id }}"
    oauth2_proxy_client_secret: "{{ sso_clients.firefly_iii.secret }}"
    oauth2_proxy_cookie_secret: "{{ firefly_iii.cookie_secret }}"
- name: Firefly III Database
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "firefly-iii-db"
    docker_service_description: "Firefly III MariaDB"
    docker_service_image: mariadb:11.8
    docker_service_network: source_default
    docker_service_user: "568"
    docker_service_group: "568"
    docker_service_env_vars:
      MYSQL_USER: firefly
      MYSQL_DATABASE: firefly
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_PASSWORD: "{{ firefly_iii.db_password }}"
    docker_service_volumes:
      - "/srv/containers/storage/ssd/firefly-iii/db:/var/lib/mysql:rw"
- name: Firefly III
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "firefly-iii"
    docker_service_description: "Firefly III App"
    docker_service_image: fireflyiii/core:version-6.2
    docker_service_network: source_default
    docker_service_env_vars:
      TZ: Europe/London
      SITE_OWNER: "{{ main_email }}"
      APP_KEY: "{{ firefly_iii.app_key }}"
      DB_CONNECTION: "mysql"
      DB_HOST: "firefly-iii-db"
      DB_DATABASE: "firefly"
      DB_USERNAME: "firefly"
      DB_PASSWORD: "{{ firefly_iii.db_password }}"
      AUTHENTICATION_GUARD: "remote_user_guard"
      AUTHENTICATION_GUARD_HEADER: "HTTP_X_FORWARDED_PREFERRED_USERNAME"
      AUTHENTICATION_GUARD_EMAIL: "HTTP_X_FORWARDED_EMAIL"
      APP_URL: "https://firefly.srv.simpson.id"
      TRUSTED_PROXIES: "*"
- name: Firefly III Data Importer
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "firefly-iii-data-importer"
    docker_service_description: "Firefly III Data Importer"
    docker_service_image: fireflyiii/data-importer:version-1.7
    docker_service_network: source_default
    docker_service_volumes:
      - "/srv/containers/storage/ssd/firefly-iii/import:/import:rw"
    docker_service_env_vars:
      TZ: Europe/London
      FIREFLY_III_URL: "http://firefly-iii:8080"
      VANITY_URL: "https://firefly.srv.simpson.id"
      FIREFLY_III_ACCESS_TOKEN: "{{ firefly_iii.data_importer_pat }}"
      NORDIGEN_ID: "{{ firefly_iii.gocardless_id }}"
      NORDIGEN_KEY: "{{ firefly_iii.gocardless_secret }}"
      TRUSTED_PROXIES: "*"
      IMPORT_DIR_ALLOWLIST: "/import"
- name: Firefly III Data Import Job
  ansible.builtin.cron:
    name: "Firefly III Data Import Job"
    user: app
    minute: "0"
    hour: "3"
    job: "/usr/bin/env docker exec firefly-iii-data-importer php artisan importer:auto-import /import >> /var/log/firefly-iii-data-importer.log 2>&1"
    state: present
