---
# Monitoring server role defaults

# State management
monitoring_server_state: present

# Storage paths
monitoring_server_storage_path: "/srv/containers/storage/ssd"

# Prometheus configuration
monitoring_server_prometheus_retention_size: "10GB"
monitoring_server_prometheus_scrape_interval: "30s"
monitoring_server_prometheus_evaluation_interval: "30s"

# Alertmanager configuration
monitoring_server_alertmanager_resolve_timeout: "5m"
monitoring_server_alertmanager_group_wait: "10s"
monitoring_server_alertmanager_group_interval: "10s"
monitoring_server_alertmanager_repeat_interval: "12h"

# Node exporter targets
monitoring_server_node_exporter_targets:
  - "little.int.simpson.id:9100"
  - "box.int.simpson.id:9100"

# SMARTCTL exporter targets
monitoring_server_smartctl_exporter_targets:
  - "little.int.simpson.id:9633"
  - "box.int.simpson.id:9633"

# Grafana configuration
monitoring_server_grafana_root_url: "https://grafana.srv.simpson.id"
monitoring_server_grafana_extra_volumes: []

# Docker service configuration
monitoring_server_network: "source_default"
monitoring_server_user: "568"
monitoring_server_group: "568"
