- name: Install Tailscale package signing key
  ansible.builtin.get_url:
    url: "https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg"
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    mode: '0644'
- name: Add Tailscale repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
    filename: tailscale
  register: tailscale_repo
- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present
    update_cache: "{{ tailscale_repo.changed }}"
- name: Enable and start Tailscale service
  ansible.builtin.systemd:
    name: tailscaled
    state: started
    enabled: true
- name: Tailscale status
  ansible.builtin.command: tailscale status
  register: tailscale_status
  changed_when: false
  failed_when: false
- name: Tailscale up
  ansible.builtin.command: >
    tailscale up
      --reset
      --auth-key={{ tailscale_oauth_key }}
      --hostname={{ ansible_hostname }}
      --advertise-tags={{ tailscale_tags | join(',') }}
  register: tailscale_up
  # tailscale status returns 130 if not connected to tailnet
  changed_when: "tailscale_status.rc == 130"
  failed_when: "tailscale_up.rc != 0"
