FROM {{ container_images.caddy }}-builder AS builder

RUN xcaddy build \
  --with github.com/mholt/caddy-webdav

FROM {{ container_images.caddy }}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD [ "/usr/bin/caddy" ]