---
- name: Remove Concourse Web data
  ansible.builtin.file:
    path: "{{ concourse_web_data_directory }}/concourse-web"
    state: absent

- name: Remove PostgreSQL data directory
  ansible.builtin.file:
    path: "{{ concourse_web_data_directory }}/postgres"
    state: absent

- name: Concourse Docker network
  community.docker.docker_network:
    name: "{{ concourse_web_network }}"
    state: "absent"