---
- name: Present tasks
  ansible.builtin.include_tasks:
    file: present.yaml
  when: concourse_web_state == 'present'

- name: PostgreSQL service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "concourse-postgres"
    docker_service_description: "Concourse PostgreSQL Database"
    docker_service_image: "{{ container_images.concourse_postgres }}"
    docker_service_network: "{{ concourse_web_network }}"
    docker_service_user: "568"
    docker_service_groups: ["568"]
    docker_service_env_vars:
      POSTGRES_USER: "{{ concourse_web_postgres_user }}"
      POSTGRES_PASSWORD: "{{ concourse_web_postgres_password }}"
      POSTGRES_DB: "{{ concourse_web_postgres_database }}"
    docker_service_volumes:
      - "{{ concourse_web_data_directory }}/postgres:/var/lib/postgresql"
    docker_service_state: "{{ concourse_web_state }}"

- name: Concourse Web service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "concourse-web"
    docker_service_description: "Concourse CI Web"
    docker_service_image: "{{ container_images.concourse_web }}"
    docker_service_network: "{{ concourse_web_network }}"
    docker_service_user: "568"
    docker_service_groups: ["568"]
    docker_service_command: "web"
    docker_service_ports:
      - "2222:2222"
    docker_service_env_vars:
      CONCOURSE_EXTERNAL_URL: "{{ concourse_web_external_url }}"
      CONCOURSE_POSTGRES_HOST: "concourse-postgres"
      CONCOURSE_POSTGRES_PORT: "5432"
      CONCOURSE_POSTGRES_USER: "{{ concourse_web_postgres_user }}"
      CONCOURSE_POSTGRES_PASSWORD: "{{ concourse_web_postgres_password }}"
      CONCOURSE_POSTGRES_DATABASE: "{{ concourse_web_postgres_database }}"
      CONCOURSE_MAIN_TEAM_LOCAL_USER: "{{ concourse_web_main_team_local_user }}"
      CONCOURSE_OIDC_DISPLAY_NAME: "Pocket ID"
      CONCOURSE_OIDC_CLIENT_ID: "{{ sso_clients.concourse.id }}"
      CONCOURSE_OIDC_CLIENT_SECRET: "{{ sso_clients.concourse.secret }}"
      CONCOURSE_OIDC_ISSUER: "{{ concourse_web_oidc_issuer }}"
      CONCOURSE_OIDC_SCOPE: "openid, profile, groups"
      CONCOURSE_ADD_LOCAL_USER: "{{ concourse_web_add_local_user }}"
      CONCOURSE_MAIN_TEAM_OIDC_GROUP: "admin"
      CONCOURSE_OIDC_USER_NAME_KEY: "preferred_username"
      CONCOURSE_SESSION_SIGNING_KEY: "/concourse-keys/session_signing_key"
      CONCOURSE_TSA_HOST_KEY: "/concourse-keys/tsa_host_key"
      CONCOURSE_TSA_AUTHORIZED_KEYS: "/concourse-keys/authorized_worker_keys"
      CONCOURSE_VAULT_URL: "{{ concourse_web_vault_url }}"
      CONCOURSE_VAULT_CLIENT_TOKEN: "{{ concourse_web_vault_token }}"
      CONCOURSE_VAULT_SHARED_PATH: "shared"
    docker_service_volumes:
      - "{{ concourse_web_data_directory }}/concourse-web/keys:/concourse-keys:ro"
    docker_service_state: "{{ concourse_web_state }}"

- name: Absent tasks
  ansible.builtin.include_tasks:
    file: absent.yaml
  when: concourse_web_state == 'absent'
