---
- name: Remove knot directories
  ansible.builtin.file:
    path: "{{ knot_directory }}"
    state: absent

- name: Remove Knot Docker network
  community.docker.docker_network:
    name: "{{ knot_network }}"
    state: absent
