---
- name: Knot Docker network
  community.docker.docker_network:
    name: "{{ knot_network }}"
    state: present

- name: Create knot directories
  ansible.builtin.file:
    path: "{{ knot_directory }}/{{ item }}"
    state: directory
    mode: '0750'
    owner: '1000'
    group: '1000'
  loop:
    - ''
    - keys
    - database
    - repositories
