- name: Pi coding agent
  hosts: 127.0.0.1
  connection: local
  become: false
  vars_files:
    - secret.yaml
  tasks:
    - name: Set facts
      ansible.builtin.set_fact:
        pi_dir: "{{ ansible_facts['user_dir'] }}/.pi/agent"

    - name: Install macos packages
      ansible.builtin.package:
        name:
          - pi-coding-agent
        state: present
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Create Pi directory
      ansible.builtin.file:
        path: "{{ pi_dir }}"
        state: directory
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: '0750'

    - name: Install custom package
      ansible.builtin.command:
        cmd: pi install https://git.sams.wtf/tophattedcat/pi.git
      register: pi_install
      changed_when: '"Cloning" in pi_install.stderr'

    - name: Update custom package
      ansible.builtin.command:
        cmd: pi update https://git.sams.wtf/tophattedcat/pi.git
      register: pi_update
      changed_when: '"HEAD is now at" in pi_update.stderr'

    - name: Create web-tools config file
      ansible.builtin.template:
        src: files/web.json.j2
        dest: "{{ pi_dir }}/web.json"
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: '0600'

    - name: Create models.json file
      ansible.builtin.copy:
        src: "files/personal-models.json"
        dest: "{{ pi_dir }}/models.json"
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: '0600'
      # no openrouter use on work mac, so don't bother creating the models file
      when: "not ansible_facts['hostname'] is match('MAC-Dev-.*')"

    # subagents aren't useful when you only have 1 model available
    - name: Create subagent config file
      ansible.builtin.copy:
        src: files/subagent.json
        dest: "{{ pi_dir }}/subagent.json"
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: '0600'
      when: "not ansible_facts['hostname'] is match('MAC-Dev-.*')"

    - name: Create bash-permissions config file
      ansible.builtin.copy:
        src: files/bash-permissions.json
        dest: "{{ pi_dir }}/bash-permissions.json"
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: '0600'

    - name: Clean up old config files
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/.pi/{{ item }}"
        state: absent
      loop:
        - web.json
        - subagent.json
