- name: Desktop Shell
  hosts: 127.0.0.1
  connection: local
  become: false
  tasks:
    - name: Set Facts (MacOS)
      ansible.builtin.set_fact:
        zsh_plugin_prefix: "/opt/homebrew/share"
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Set Facts (Linux)
      ansible.builtin.set_fact:
        zsh_plugin_prefix: "/usr/share/zsh/plugins"
      when: ansible_facts['os_family'] == 'Archlinux'

    - name: Install packages
      ansible.builtin.package:
        name:
          - fzf
          - mise
          - rbenv
          - zsh
          - zsh-autosuggestions
          - zsh-completions
          - zsh-syntax-highlighting
          - starship
        state: present
      become: "{{ ansible_facts['os_family'] == 'Archlinux' }}"

    - name: Create zshrc
      ansible.builtin.template:
        src: files/zshrc.j2
        dest: "{{ ansible_facts['user_dir'] }}/.zshrc"
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: '0750'

    - name: Create starship config
      ansible.builtin.copy:
        src: files/starship.toml
        dest: "{{ ansible_facts['user_dir'] }}/.config/starship.toml"
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: '0640'

    - name: Create zshrc.d directory
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/.zshrc.d"
        state: directory
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: '0750'

    - name: Create ghostty config directory
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/.config/ghostty"
        state: directory
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: '0700'
      when: ansible_facts['os_family'] == 'Archlinux'

    - name: Create ghostty config
      ansible.builtin.copy:
        dest: "{{ ansible_facts['user_dir'] }}/.config/ghostty/config"
        src: files/ghostty
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: '0600'
      when: ansible_facts['os_family'] == 'Archlinux'
