---
- name: Remove Vault directories
  ansible.builtin.file:
    path: "{{ vault_directory }}"
    state: absent

- name: Vault Docker network
  community.docker.docker_network:
    name: "{{ vault_network }}"
    state: absent

- name: Remove Vault user
  ansible.builtin.user:
    name: vault
    state: absent

- name: Remove Vault health pusher cron job
  ansible.builtin.cron:
    name: "Vault Health Pusher"
    user: vault
    state: absent
