---
- name: Present tasks
  ansible.builtin.include_tasks:
    file: present.yaml
  when: vault_state == 'present'

- name: Vault service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: vault
    docker_service_command: "vault server -config /config.hcl"
    docker_service_image: "{{ container_images.vault }}"
    docker_service_network: "{{ vault_network }}"
    docker_service_user: "{{ vault_uid }}"
    docker_service_volumes:
      - "{{ vault_directory }}/data:/data"
      - "{{ vault_directory }}/config.hcl:/config.hcl"
    docker_service_capabilities:
      - IPC_LOCK
    docker_service_env_vars:
      SKIP_SETCAP: "true"
      SKIP_CHOWN: "true"
    docker_service_state: "{{ vault_state }}"

- name: Absent tasks
  ansible.builtin.include_tasks:
    file: absent.yaml
  when: vault_state == 'absent'
