- name: Present tasks
  ansible.builtin.include_tasks:
    file: present.yaml
  when: ha_proxy_state == 'present'

- name: Caddy service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "caddy-ha"
    docker_service_description: "Caddy ha"
    docker_service_image: "localhost/ha-{{ container_images.caddy }}"
    docker_service_pull_policy: "never"
    docker_service_network: "host"
    docker_service_command: "caddy run -c /Caddyfile"
    docker_service_env_vars: {}
    docker_service_ports:
      - "6999:6999"
      - "6998:6998"
    docker_service_volumes:
      - "{{ ha_proxy_directory }}/config:/config"
      - "{{ ha_proxy_directory }}/data:/data"
      - "{{ ha_proxy_directory }}/Caddyfile:/Caddyfile"
      - "/srv/certificates:/certificates:ro"
    docker_service_state: "{{ ha_proxy_state }}"

- name: Absent tasks
  ansible.builtin.include_tasks:
    file: absent.yaml
  when: ha_proxy_state == 'absent'
