- name: Caddy data directories
  ansible.builtin.file:
    path: "{{ ha_proxy_directory }}/{{ item }}"
    state: directory
    owner: app
    group: app
    mode: '0750'
  loop:
    - ""
    - config
    - data
  when: ha_proxy_state == 'present'

- name: Install ha packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - keepalived
  when: ha_proxy_state == 'present'

- name: Create keepalived config file
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart keepalived service
  when: ha_proxy_state == 'present'

- name: Enable and start keepalived
  ansible.builtin.service:
    name: keepalived
    enabled: true
    state: started
  when: ha_proxy_state == 'present'

- name: Dockerfile
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: "{{ ha_proxy_directory }}/Dockerfile"
    owner: app
    group: app
    mode: '0644'
  notify: "Restart caddy ha service"
  when: ha_proxy_state == 'present'

- name: Caddy image
  community.docker.docker_image_build:
    name: "localhost/ha-{{ container_images.caddy }}"
    path: "{{ ha_proxy_directory }}"
  notify: "Restart caddy ha service"
  when: ha_proxy_state == 'present'

- name: Caddy config file
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ ha_proxy_directory }}/Caddyfile"
    owner: root
    group: root
    mode: '0644'
    lstrip_blocks: true
  notify: Restart caddy ha service
  when: ha_proxy_state == 'present'

- name: Caddy service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "caddy-ha"
    docker_service_description: "Caddy ha"
    docker_service_image: "localhost/ha-{{ container_images.caddy }}"
    docker_service_pull_policy: "never"
    docker_service_network: "host"
    docker_service_command: "caddy run -c /Caddyfile"
    docker_service_env_vars: {}
    docker_service_ports:
      - "6999:6999"
      - "6998:6998"
    docker_service_volumes:
      - "{{ ha_proxy_directory }}/config:/config"
      - "{{ ha_proxy_directory }}/data:/data"
      - "{{ ha_proxy_directory }}/Caddyfile:/Caddyfile"
      - "/srv/certificates:/certificates:ro"
    docker_service_state: "{{ ha_proxy_state }}"

# Removal tasks
- name: Stop and disable keepalived
  ansible.builtin.service:
    name: keepalived
    enabled: false
    state: stopped
  when: ha_proxy_state == 'absent'

- name: Remove keepalived config file
  ansible.builtin.file:
    path: /etc/keepalived/keepalived.conf
    state: absent
  when: ha_proxy_state == 'absent'

- name: Remove Caddy config file
  ansible.builtin.file:
    path: "{{ ha_proxy_directory }}/Caddyfile"
    state: absent
  when: ha_proxy_state == 'absent'

- name: Remove Dockerfile
  ansible.builtin.file:
    path: "{{ ha_proxy_directory }}/Dockerfile"
    state: absent
  when: ha_proxy_state == 'absent'

- name: Remove Caddy data directories
  ansible.builtin.file:
    path: "{{ ha_proxy_directory }}"
    state: absent
  when: ha_proxy_state == 'absent'
