- name: Create systemd service unit
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/{{ docker_service_id }}.service
    mode: "0644"
  notify: "Restart {{ docker_service_id }} service"
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: "{{ docker_service_id }}"
    state: started
    enabled: "{{ docker_service_enabled }}"
