- name: Present tasks
  ansible.builtin.include_tasks:
    file: present.yaml
  when: offline_backup_state == 'present'
- name: Absent tasks
  ansible.builtin.include_tasks:
    file: absent.yaml
  when: offline_backup_state == 'absent'
