---
- name: Concourse Worker data directory
  ansible.builtin.file:
    path: "{{ concourse_worker_data_directory }}"
    state: directory
    owner: app
    group: app
    mode: '0755'
  when: concourse_worker_state == 'present'

- name: Concourse Worker keys directory
  ansible.builtin.file:
    path: "{{ concourse_worker_data_directory }}/keys"
    state: directory
    owner: app
    group: app
    mode: '0700'
  when: concourse_worker_state == 'present'

- name: Concourse Worker TSA public key
  ansible.builtin.copy:
    content: "{{ concourse_worker_tsa_public_key }}"
    dest: "{{ concourse_worker_data_directory }}/keys/tsa_host_key.pub"
    owner: app
    group: app
    mode: '0600'
  when: concourse_worker_state == 'present'

- name: Concourse Worker private key
  ansible.builtin.copy:
    content: "{{ concourse_worker_worker_key }}"
    dest: "{{ concourse_worker_data_directory }}/keys/worker_key"
    owner: app
    group: app
    mode: '0600'
  when: concourse_worker_state == 'present'

- name: Concourse Worker state directory
  ansible.builtin.file:
    path: "{{ concourse_worker_data_directory }}/work"
    state: directory
    owner: app
    group: app
    mode: '0755'
  when: concourse_worker_state == 'present'

- name: Concourse Worker service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "concourse-worker"
    docker_service_description: "Concourse CI Worker"
    docker_service_image: "{{ container_images.concourse_worker }}"
    docker_service_user: "root"
    docker_service_command: "worker"
    docker_service_privileged: true
    docker_service_cgroupns: host
    docker_service_env_vars:
      CONCOURSE_TSA_HOST: "{{ concourse_worker_tsa_host }}"
      CONCOURSE_TSA_PUBLIC_KEY: "/concourse-keys/tsa_host_key.pub"
      CONCOURSE_TSA_WORKER_PRIVATE_KEY: "/concourse-keys/worker_key"
      CONCOURSE_WORK_DIR: "{{ concourse_worker_data_directory }}/work"
      CONCOURSE_RUNTIME: guardian
    docker_service_volumes:
      - "{{ concourse_worker_data_directory }}/keys:/concourse-keys:ro"
      - "{{ concourse_worker_data_directory }}/work:{{ concourse_worker_data_directory }}/work"
    docker_service_state: "{{ concourse_worker_state }}"

- name: Remove Concourse Worker data directory
  ansible.builtin.file:
    path: "{{ concourse_worker_data_directory }}"
    state: absent
  when: concourse_worker_state == 'absent'
