docker_service_description: "Docker Service"
docker_service_id: docker_service
docker_service_image: hashicorp/http-echo:latest
docker_service_command: null
docker_service_pull_policy: always
docker_service_ports: []
docker_service_volumes: []
docker_service_env_vars: {}
docker_service_enabled: true
docker_service_network: null
docker_service_user: null
docker_service_groups: []
docker_service_devices: []
docker_service_privileged: false
docker_service_pid: null
docker_service_cgroupns: null
docker_service_state: present
docker_service_capabilities: []
docker_service_extra_systemd_content: ""
docker_service_dns_search: "int.simpson.id"