- name: Create arr data directories
  ansible.builtin.file:
    state: directory
    path: "/srv/containers/storage/ssd/{{ item }}"
    mode: "0750"
    owner: "app"
    group: "app"
  loop:
    - prowlarr
    - radarr
    - sonarr
- name: Prowlarr service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "prowlarr"
    docker_service_description: "Prowlarr"
    docker_service_image: ghcr.io/home-operations/prowlarr:1.37
    docker_service_network: source_default
    docker_service_user: "568"
    docker_service_group: "568"
    docker_service_env_vars:
      TZ: Europe/London
      PROWLARR__PORT: "80"
    docker_service_volumes:
      - "/srv/containers/storage/ssd/prowlarr:/config:rw"
- name: Radarr service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "radarr"
    docker_service_description: "Radarr"
    docker_service_image: ghcr.io/home-operations/radarr:5.28.0
    docker_service_network: source_default
    docker_service_user: "568"
    docker_service_group: "568"
    docker_service_env_vars:
      TZ: Europe/London
      RADARR__PORT: "80"
    docker_service_volumes:
      - "/srv/containers/storage/ssd/radarr:/config:rw"
      - "/srv/containers/storage/hdd/media:/media:rw"
- name: Sonarr service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "sonarr"
    docker_service_description: "Sonarr"
    docker_service_image: ghcr.io/home-operations/sonarr:4.0.15
    docker_service_network: source_default
    docker_service_user: "568"
    docker_service_group: "568"
    docker_service_env_vars:
      TZ: Europe/London
      SONARR__PORT: "80"
    docker_service_volumes:
      - "/srv/containers/storage/ssd/sonarr:/config:rw"
      - "/srv/containers/storage/hdd/media:/media:rw"
