- name: ShareX SSH key
  ansible.posix.authorized_key:
    user: app
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMSjn6O+qaATVQ9r5ZZJol840Q1uKVu0ZrwErYNNTNvM sam@sampc"
- name: Caddy external
  ansible.builtin.include_role:
    name: caddy
  vars:
    caddy_id: "external"
    caddy_https_port: "6997"
    caddy_http_port: "6996"
    caddy_env_vars:
      CADDY_CLOUDFLARE_API_KEY: "{{ cloudflare_api_key }}"
    caddy_volumes:
      - "/srv/containers/storage/hdd/files:/webdav-files"
      - "/srv/containers/storage/ssd/sharex:/sharex"
    caddy_hosts:
      - name: "srv.simpson.id"
        wildcard: true
        sites:
          - name: audiobookshelf
            target: "http://audiobookshelf:8080"
          - name: bookmarks
            target: "http://karakeep-web:3000"
          - name: budget
            target: "http://actual:5006"
          - name: files
            custom: |
              @files host files.srv.simpson.id
              handle @files {
                route {
                  basic_auth {
                    me {{ webdav_basic_auth_password_hash }}
                  }
                  webdav {
                    root /webdav-files
                  }
                }
              }
          - name: firefly
            target: "http://firefly-oauth2-proxy:4180"
          - name: grafana
            target: "http://grafana:3000"
          - name: hass
            target: "http://10.0.0.191:8123"
          - name: jellyfin
            target: "http://10.0.0.191:8096"
          - name: comics
            target: "http://komga:25600"
          - name: navidrome
            target: "http://navidrome:4533"
          - name: pathfinder
            target: "http://pathfinder:80"
          - name: pinchflat
            target: "http://pinchflat-oauth2-proxy:4180"
          - name: pocket-id
            target: "http://pocket-id:1411"
          - name: rss
            target: "http://freshrss:80"
          - name: requests
            target: "http://overseerr:80"
          - name: sharex
            custom: |
              @sharex host sharex.srv.simpson.id
              handle @sharex {
                root * /sharex
                file_server
              }
      - name: sams.wtf
        sites: []
        fallback: |
          handle {
            respond "Nothing to see here."
          }
