- name: Caddy internal
  ansible.builtin.include_role:
    name: caddy
  vars:
    caddy_id: "internal"
    caddy_https_port: "443"
    caddy_http_port: "80"
    caddy_env_vars:
      CADDY_CLOUDFLARE_API_KEY: "{{ cloudflare_api_key }}"
    caddy_hosts: "{{ sites[ansible_hostname] | selectattr('kind', 'equalto', 'internal') }}"