- name: ShareX SSH key
  ansible.posix.authorized_key:
    user: app
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMSjn6O+qaATVQ9r5ZZJol840Q1uKVu0ZrwErYNNTNvM sam@sampc"

- name: Caddy external
  ansible.builtin.include_role:
    name: caddy
  vars:
    caddy_id: "external"
    caddy_https_port: "6997"
    caddy_http_port: "6996"
    caddy_env_vars: {}
    caddy_volumes:
      - "/srv/containers/storage/hdd/files:/webdav-files"
      - "/srv/containers/storage/ssd/sharex:/sharex"
    caddy_hosts: "{{ sites | selectattr('kind', 'equalto', 'external') }}"

- name: Caddy internal
  ansible.builtin.include_role:
    name: caddy
  vars:
    caddy_id: "internal"
    caddy_https_port: "443"
    caddy_http_port: "80"
    caddy_env_vars: {}
    caddy_hosts: "{{ sites | selectattr('kind', 'equalto', 'internal') }}"
    caddy_networks: ["source_default", "vault"]
