- name: Create downloader data directories
  ansible.builtin.file:
    state: directory
    path: "/srv/containers/storage/ssd/{{ item }}"
    mode: "0750"
    owner: "app"
    group: "app"
  loop:
    - qbittorrent
    - sabnzbd
    - slskd
- name: QBittorrent service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "qbittorrent"
    docker_service_description: "qBittorrent"
    docker_service_image: ghcr.io/home-operations/qbittorrent:5.1.2
    docker_service_network: source_default
    docker_service_user: "568"
    docker_service_groups: ["568"]
    docker_service_env_vars:
      TZ: Europe/London
      QBITTORRENT__PORT: "80"
      QBITTORRENT__BT_PORT: "32760"
    docker_service_volumes:
      - "/srv/containers/storage/ssd/qbittorrent:/config:rw"
      - "/srv/containers/storage/hdd/media:/media:rw"
    docker_service_ports:
      - "32760:32760"
- name: SABnzbd service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "sabnzbd"
    docker_service_description: "SABnzbd"
    docker_service_image: ghcr.io/home-operations/sabnzbd:4.5.5
    docker_service_network: source_default
    docker_service_user: "568"
    docker_service_groups: ["568"]
    docker_service_env_vars:
      TZ: Europe/London
      SABNZBD__PORT: "80"
      SABNZBD__HOST_WHITELIST_ENTRIES: "sabnzbd, sabnzbd.int.simpson.id"
    docker_service_volumes:
      - "/srv/containers/storage/ssd/sabnzbd:/config:rw"
      - "/srv/containers/storage/hdd/media:/media:rw"

- name: Unpackerr service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "unpackerr"
    docker_service_description: "Unpackerr"
    docker_service_image: ghcr.io/unpackerr/unpackerr:0.14.5
    docker_service_network: source_default
    docker_service_user: "568"
    docker_service_groups: ["568"]
    docker_service_env_file: "/srv/containers/storage/ssd/secrets/Unpackerr.env"
    docker_service_env_vars:
      UN_RADARR_0_URL: "https://radarr.int.simpson.id"
      UN_RADARR_0_PATHS_0: "/media/torrent"
      UN_SONARR_0_URL: "https://sonarr.int.simpson.id"
      UN_SONARR_0_PATHS_0: "/media/torrent"
    docker_service_volumes:
      - "/srv/containers/storage/hdd/media:/media:rw"

- name: Slskd service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "slskd"
    docker_service_description: "Slskd"
    docker_service_image: slskd/slskd:0.23.2
    docker_service_network: source_default
    docker_service_user: "568"
    docker_service_groups: ["568"]
    docker_service_env_vars:
      SLSKD_REMOTE_CONFIGURATION: "true"
    docker_service_ports:
      - "34000:34000"
    docker_service_volumes:
      - "/srv/containers/storage/ssd/slskd:/app:rw"
      - "/srv/containers/storage/hdd/media:/media:rw"
