- name: Create monitoring data directories
  ansible.builtin.file:
    state: directory
    path: "/srv/containers/storage/ssd/{{ item }}"
    mode: "0750"
    owner: "app"
    group: "app"
  loop:
    - grafana
    - prometheus

- name: Create Prometheus configuration file
  ansible.builtin.copy:
    content: |
      scrape_configs:
        - job_name: "prometheus"
          static_configs:
            - targets: ["little.int.simpson.id:9100"]
              labels:
                host: little
    dest: /srv/containers/storage/ssd/prometheus/config.yaml
    mode: "0644"
    owner: "app"
    group: "app"

- name: Prometheus Node Exporter service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "prometheus-node-exporter"
    docker_service_description: "Prometheus Node Exporter"
    docker_service_image: prom/node-exporter:v1.9.1
    docker_service_network: host
    docker_service_pid: host
    docker_service_command: "--path.rootfs=/host"
    docker_service_volumes:
      - "/:/host:ro,rslave"

- name: Prometheus service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "prometheus"
    docker_service_description: "Prometheus"
    docker_service_image: prom/prometheus:v2.55.1
    docker_service_network: source_default
    docker_service_user: "568"
    docker_service_groups: ["568"]
    docker_service_command: "--storage.tsdb.path /data --storage.tsdb.retention.size 10GB --config.file /config.yaml"
    docker_service_volumes:
      - "/srv/containers/storage/ssd/prometheus:/data:rw"
      - "/srv/containers/storage/ssd/prometheus/config.yaml:/config.yaml:ro"

- name: Grafana service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "grafana"
    docker_service_description: "Grafana"
    docker_service_image: grafana/grafana:11.6.7
    docker_service_network: source_default
    docker_service_user: "568"
    docker_service_groups: ["568"]
    docker_service_env_vars:
      GF_SERVER_ROOT_URL: "https://grafana.srv.simpson.id"
    docker_service_volumes:
      - "/srv/containers/storage/ssd/grafana:/var/lib/grafana:rw"
      - "/srv/containers/storage/ssd/stonks:/stonks:rw"
      - "/srv/containers/storage/ssd/nutrition:/nutrition:rw"
