- name: Pocket ID data directory
  ansible.builtin.file:
    path: /srv/containers/storage/ssd/pocket-id
    state: directory
    mode: '0750'
    owner: app
    group: app
- name: Pocket ID service
  include_role:
    name: docker-service
  vars:
    id: "pocket-id"
    description: "Pocket ID"
    image: ghcr.io/pocket-id/pocket-id:v1
    network: source_default
    env_vars:
      APP_URL: "https://pocket-id.srv.simpson.id"
      TRUST_PROXY: "true"
      PUID: "568"
      PGID: "568"
      DB_CONNECTION_STRING: "file:/data/pocket-id.db?_pragma=journal_mode(WAL)&_pragma=busy_timeout(2500)&_txlock=immediate"
      UPLOAD_PATH: "/data/uploads"
      KEYS_PATH: "/data/keys"
      UI_CONFIG_DISABLED: "true"
      SMTP_FROM: "pocket-id@ses.simpson.id"
      SMTP_USER: "{{ smtp_username }}"
      SMTP_PASSWORD: "{{ smtp_password }}"
      SMTP_HOST: "{{ smtp_hostname }}"
      SMTP_PORT: "{{ smtp_port }}"
      SMTP_TLS: "{{ smtp_tls }}"
    volumes:
      - "/srv/containers/storage/ssd/pocket-id:/data"