- name: Stonks scraper data directory
  ansible.builtin.file:
    state: directory
    path: "/srv/containers/storage/ssd/stonks"
    mode: "0750"
    owner: app
    group: app
- name: Stonks scraper service
  ansible.builtin.include_role:
    name: docker_service
  vars:
    docker_service_id: "stonks-scraper"
    docker_service_description: "Stonks scraper"
    docker_service_image: "ghcr.io/samsimpson1/stonks:latest"
    docker_service_network: source_default
    docker_service_user: "568"
    docker_service_group: "568"
    docker_service_volumes:
      - "/srv/containers/storage/ssd/stonks:/data:rw"
