---
- name: Restart Pocket ID
  ansible.builtin.systemd:
    name: "pocket-id"
    state: restarted
    daemon_reload: false
  when: pocket_id_role == 'primary'

- name: Restart Litestream
  ansible.builtin.systemd:
    name: "pocket-id-litestream"
    state: restarted
    daemon_reload: false
