name: Ansible Lint

on:
  push:

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install ansible
      
      - name: Install Ansible requirements
        run: |
          ansible-galaxy install -r requirements.yaml

      - name: Install 1Password CLI
        run: |
          curl -sS https://downloads.1password.com/linux/keys/1password.asc | \
            sudo gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/$(dpkg --print-architecture) stable main" | \
            sudo tee /etc/apt/sources.list.d/1password.list
          sudo apt update
          sudo apt install -y 1password-cli
      
      - name: Configure 1Password CLI
        run: |
          echo "OP_SERVICE_ACCOUNT_TOKEN=${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}" >> $GITHUB_ENV

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          setup_python: "false"
          working_directory: "."