- name: Work Mac Packages
  hosts: 127.0.0.1
  connection: local
  become: false
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - 1password
          - actionlint
          - ansible
          - ansible-lint
          - awscli
          - claude-code@latest
          - firefox
          - fzf
          - gh
          - ghostty
          - obsidian
          - rbenv
          - ripgrep
          - slack
          - tenv
          - uv
          - visual-studio-code
          - ykman
          - yubico-authenticator

    - name: Create Ghostty config dir
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/.config/ghostty"
        state: directory
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: '0700'

    - name: Create Ghostty config
      ansible.builtin.copy:
        content: |
          shell-integration-features = ssh-env
          theme = Catppuccin Latte
        dest: "{{ ansible_facts['user_dir'] }}/.config/ghostty/config"
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: '0640'
