- name: Linux packages
  ansible.builtin.import_playbook: play-linux-packages.yaml
- name: Shell
  ansible.builtin.import_playbook: shell/playbook.yaml
- name: SSH Shell
  ansible.builtin.import_playbook: shell-ssh/playbook.yaml
