- name: Work Mac Packages
  hosts: 127.0.0.1
  connection: local
  become: false
  tasks:
    - name: Tap casks
      community.general.homebrew_tap:
        name:
          - goreleaser/tap

    - name: Install packages
      ansible.builtin.package:
        name:
          - actionlint
          - ansible
          - ansible-lint
          - awscli
          - caffeine
          - chart-releaser
          - claude-code@latest
          - docker-desktop
          - firefox@nightly
          - fzf
          - gcloud-cli
          - gh
          - ghostty
          - go
          - goreleaser/tap/goreleaser
          - k3d
          - keepassxc
          - kind
          - krew
          - kubebuilder
          - obsidian
          - rbenv
          - ripgrep
          - slack
          - tenv
          - uv
          - visual-studio-code
          - ykman
          - yq
          - yubico-authenticator

    - name: Create Ghostty config dir
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/.config/ghostty"
        state: directory
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: '0700'

    - name: Create Ghostty config
      ansible.builtin.copy:
        content: |
          shell-integration-features = ssh-env
          theme = Catppuccin Mocha
        dest: "{{ ansible_facts['user_dir'] }}/.config/ghostty/config"
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: '0640'

    # Firefox Nightly doesn't ship with a wrapper script for the firefox executable
    - name: Create firefox wrapper script
      ansible.builtin.copy:
        content: |
          #!/usr/bin/env bash
          exec '/Applications/Firefox Nightly.app/Contents/MacOS/firefox' "$@"
        dest: "{{ ansible_facts['user_dir'] }}/bin/firefox"
        owner: "{{ ansible_facts['user_id'] }}"
        group: "{{ ansible_facts['user_gid'] }}"
        mode: '0750'